---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: svc-rc1
  labels: 
    app: nginx 
    layer: web 
spec: 
  minReadySeconds: 1
  replicas: 2
  selector: 
    matchLabels: 
      app: nginx 
  template:
    metadata:
      name: nginx 
      labels:
        app: nginx 
    spec: 
      containers: 
        - name: nginx 
          image: nginx 
          ports: 
            - containerPort: 80 