---
apiVersion: apps/v1 
kind: DaemonSet 
metadata: 
  name: demo-set
  annotations:
    kubernetes.io/change-cause: "updated to fluentd"
  labels: 
    app: fluentd
spec:
  minReadySeconds: 2
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      name: fluentd
      labels: 
        app: fluentd 
    spec: 
      containers:
        - name: fluentd
          iamge: fluentd