---
apiVersion: apps/v1 
kind: DaemonSet
metadata:
  name: deamon-set
  labels: 
    app: fluentd
spec:  
  minReadySeconds: 1
  selector: 
    matchLabels: 
      app: fluentd
  template: 
    metadata: 
      name: fluentd
      labels:
        app: fluentd
    spec: 
      containers: 
        - name: fluentd
          image: fluentd:v1.16-debian-1


        