---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: deploy-nginx 
  labels:
    app: deploy-nginx 
spec: 
  minReadySeconds: 5
  replicas: 3 
  selector: 
    app: nginx 
    ver: "1.23" 
  strategy: 
    type: rollingUpdate
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
  template: 
    metadata: 
      name: nginx 
      labels: 
        app: nginx 
        ver: "1.23" 
    spec: 
      containers: 
        - name: nginx 
          image: nginx 
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: 
            path: /
            port: 80 
          resources: 
            requests: 
              memory: "256Mi"
              cpu: "500m" 
            limits:
              memory: "1000Mi" 
              cpu: "2000m" 

  

