---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: deploy-nginx 
  labels:
    app: deploy-nginx 
spec: 
  minReadySeconds: 5
  replicas: 3 
  selector: 
    matchLabels: 
      app: nginx 
  strategy: 
    type: rollingUpdate
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
  template: 
    metadata: 
      name: nginx 
      labels: 
        app: nginx  
    spec: 
      containers: 
        - name: nginx 
          image: nginx 
          ports:
            - containerPort: 80
       

  

