--- 
apiVersion: v1 
kind: Pod 
metadata:
  name: initcontainer
spec:
  containers:
    - name: httpd
      image: httpd 
      ports: 
        - containerPort: 80
  initContainers: 
    - command:
        - "sh"
        - "-c"
        - "until nslookup init-svc.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done"

