---
apiVersion: batch/v1 
kind: Job
metadata:
  name: chinnujob
spec:
  backoffLimit: 2
  template:
    metadata:
      name: jobpod
    spec: 
      restartPolicy: OnFailure
      containers:
        - name: alpine 
          image: alpine 
          args:
            - sleep 
            - 5s