---
apiVersion: v1
kind: Pod 
metadata: 
  name: httpd-pod 
spec: 
  containers:
    - name: httpd-pod 
      image: httpd 
      ports:
        - containerPort: 80
    - name: alpine 
      image: alpine 
      args:
        - sleep 
        - 1d