---
apiVersion: v1 
kind: Pod 
metadata: 
  name: mysql-cm 
spec: 
  containers:
    - name: mysql 
      image: mysql 
      envFrom: 
        - configMapRef: 
          name: mysql-config
          optional: false
          ports: 
            - containerPort: 3306
