---
apiVersion: apps/v1	
kind: ReplicaSet
metadata: 
  name: rsnew
spec: 
  minReadySeconds: 2
  replicas: 3
  selector: 
    matchLabels:
      app: httpd
  template: 
    metadata:
      name: httpd-pod
      labels:
        app: httpd
    spec:
      containers: 
        - name: httpd
          image: httpd
          ports: 
            - containerPort: 80