---
apiVersion: v1
kind: Service
metadata:
  name: httpd-srv
  labels:
    app: httpd
spec:
  ports:
    - name: httpd
      port: 80
      targetPort: 80
  selector:
    app: httpd
  type: LoadBalancer

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-httpd
  labels:
    app: httpd
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      name: httpd
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort : 80
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /
              port: 80
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /
              port: 80