---
apiVersion: v1 
kind: Service
metadata: 
  name: state-svc
spec:
  ports: 
    - name: nginx
      port: 80
      targetPort: 80 
  selector: 
    app: nginx 
  type: ClusterIP
  clusterIP: None 
